##Mate Primer for Al

In [12]:
import numpy as np

##Matrix multiplication

In [13]:
a =np.array([[1,-3,2],[4,0,-5]])
print(a)

[[ 1 -3  2]
 [ 4  0 -5]]


In [14]:
a.shape

(2, 3)

In [15]:
b = np.array([[3], [1], [2]]) 
print(b)


[[3]
 [1]
 [2]]


In [16]:
c = np.matmul(a, b) 
print(c)

[[4]
 [2]]


In [17]:
d = np.dot(a, b) 
print(d)

[[4]
 [2]]


In [18]:
d.shape

(2, 1)